apiVersion: v2
name: coprocessor
description: Helm chart for deploying the coprocessor integration.
type: application
version: 0.4.3
home: https://github.com/rtbot-dev/coprocessor-helm-chart
sources:
  - https://github.com/rtbot-dev/coprocessor-helm-chart
