{{- if and .Values.secret.create .Values.secret.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coprocessor.secretName" . }}
  labels:
    {{- include "coprocessor.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.secret.annotations }}
  annotations:
    {{- include "coprocessor.annotations" . | nindent 4 }}
    {{- with .Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
