{{- if and (not .Values.sql.existingConfigMap) (or .Values.sql.files .Values.demo.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coprocessor.sqlConfigMapName" . }}
  labels:
    {{- include "coprocessor.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.demo.enabled }}
  {{ .Values.demo.sqlFileName }}: |
{{ .Files.Get "files/demo/demo-signals.sql" | indent 4 }}
  {{- end }}
  {{- range $name, $content := .Values.sql.files }}
  {{ $name }}: |
{{ tpl $content $ | indent 4 }}
  {{- end }}
{{- end }}
